### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by pmaingi** [uldisn/d2app#4]
Has composer.json changed from below ?
{
    "name": "uldisn/eu_app",
    "description": "EU ERP",
    "keywords": ["erp","yii","phundament"],
    "type": "yii-app",
    "license": "BSD-2-Clause",
    "authors": [
        {
            "name": "Uldis Nelsons",
            "email": "uldisnelsons@gmail.com"
        }
    ],
     "require": {
        "php": ">=5.3.0",
        "dbrisinajumi/audittrail": "dev-master",
        "vitalets/x-editable-yii": "dev-master",
        "uldisn/ace": "dev-master",
        "dbrisinajumi/d2person": "dev-master",
        "dbrisinajumi/trucks": "dev-master",        
        "dbrisinajumi/d2finv": "dev-master",
        "dbrisinajumi/d2fixr": "dev-master",
        "dbrisinajumi/yeeki": "dev-master"
     }    
}
Am trying to build this application with composer and i keep on getting 
"Your requirements could not be resolved to an installable set of packages."
Problem 1
    - Installation request for dbrisinajumi/audittrail dev-master -> satisfiable by dbrisinajumi/audittrail[dev-master].
    - dbrisinajumi/audittrail dev-master requires yiiext/fancybox-widget dev-master -> no matching package found.
  Problem 2
    - Installation request for dbrisinajumi/d2person dev-master -> satisfiable by dbrisinajumi/d2person[dev-master].
    - dbrisinajumi/d2person dev-master requires dbrisinajumi/d2files dev-master -> no matching package found.
 etc
    - Installation request for uldisn/ace dev-master -> satisfiable by uldisn/ace[dev-master].
How do i resolve this issue ?

**Comment by uldisn** [comment]
I translate https://github.com/uldisn/d2app/blob/master/README.md to english (bad english).
This is draft of draft!
1. 2dapp must by in vendor/uldisn/app_d2app. in Your case vendor/jadulled/d2app
2. Load fancybox: php composer.phar require yiiext/fancybox-widget dev-master
3. load audittrail: php composer.phar require dbrisinajumi/audittrail dev-master
4. load required packages while is ok. My be I am wrong in usage composer, but that work.

**Comment by pmaingi** [comment]
Am following your steps. Once successful will let you know. Thanks alot

On Tue, Jan 20, 2015 at 3:58 PM, Uldis Nelsons <notifications@github.com>
wrote:

> I translate https://github.com/uldisn/d2app/blob/master/README.md to
> english (bad english).
> This is draft of draft!
> 1. 2dapp must by in vendor/uldisn/app_d2app. in Your case
> vendor/jadulled/d2app
> 2. Load fancybox: php composer.phar require yiiext/fancybox-widget
> dev-master
> 3. load audittrail: php composer.phar require dbrisinajumi/audittrail
> dev-master
> 4. load required packages while is ok. My be I am wrong in usage composer,
> but that work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uldisn/d2app/issues/4#issuecomment-70649381>.
>



-- 
pmaingi@gmail.com

Tel: 254 720 244970
No man in the world has more courage than the man who can stop after eating
one peanut.
